[package]
name = "cryptoki"
version = "0.3.0"
authors = ["Contributors to the Parsec project"]
edition = '2018'
description = "Rust-native wrapper around the PKCS #11 API"
readme = "README.md"
keywords = ["pkcs11", "cryptoki", "hsm"]
categories = ["api-bindings", "external-ffi-bindings", "cryptography", "hardware-support"]
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/rust-cryptoki"
documentation = "https://docs.rs/crate/cryptoki"

[dependencies]
bitflags = "1.3"
libloading = "0.7.0"
log = "0.4.14"
derivative = "2.2.0"
psa-crypto = { git = "https://github.com/parallaxsecond/rust-psa-crypto", rev = "22ebb4d8e479e1c0d853398cf8487d6389b1ed6f", default-features = false, optional = true }
cryptoki-sys = { path = "../cryptoki-sys", version = "0.1.3" }
paste = "1.0.6"

[dev-dependencies]
num-traits = "0.2.14"
hex = "0.4.3"
serial_test = "0.5.1"

[features]
psa-crypto-conversions = ["psa-crypto"]
generate-bindings = ["cryptoki-sys/generate-bindings"]
